export const quoteDetails = [
  {
    id: 1,
    pageName: "janitorial-services-nyc",
    title: "NYC Janitorial Services",
    subtitle: "Professional Janitorial Services for NYC Businesses",
    desc: "Daily janitorial care from a licensed, insured NYC team — consistent results, every visit.",
    list: [
      "Licensed & Insured Crews",
      "Flexible Daily Schedules",
      "Eco-Friendly Supplies",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 2,
    pageName: "healthcare-facility-cleaning-nyc",
    title: "Healthcare Facility Cleaning",
    subtitle: "Medical-Grade Cleaning for NYC Healthcare Facilities",
    desc: "OSHA-compliant disinfection and sanitation trusted by NYC clinics, offices, and care facilities.",
    list: [
      "OSHA-Compliant Protocols",
      "Hospital-Grade Disinfectants",
      "Trained Healthcare Crews",
      "Flexible Off-Hours Service",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 3,
    pageName: "school-cleaning-nyc",
    title: "School Cleaning Services",
    subtitle: "Safe, Reliable School Cleaning Across NYC",
    desc: "Keeping NYC schools clean and safe with vetted crews and child-safe cleaning products.",
    list: [
      "Background-Checked Staff",
      "Child-Safe Cleaning Products",
      "Before & After-Hours Service",
      "Summer Deep-Clean Programs",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 4,
    pageName: "commercial-office-cleaning-nyc",
    title: "Commercial Office Cleaning",
    subtitle: "Office Cleaning Services for NYC Businesses",
    desc: "Reliable office cleaning that keeps your NYC workspace spotless and client-ready.",
    list: [
      "Custom Cleaning Schedules",
      "Restroom & Kitchen Care",
      "Trash & Recycling Removal",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 5,
    pageName: "commercial-cleaning-services-manhattan-nyc",
    title: "Manhattan Commercial Cleaning",
    subtitle: "Commercial Cleaning Services in Manhattan, NYC",
    desc: "Trusted commercial cleaning for Manhattan offices, retail, and high-rise buildings.",
    list: [
      "High-Rise Building Experience",
      "Fully Insured & Bonded",
      "Flexible After-Hours Access",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 6,
    pageName: "commercial-cleaning-brooklyn",
    title: "Brooklyn Commercial Cleaning",
    subtitle: "Commercial Cleaning Services in Brooklyn, NY",
    desc: "Dependable commercial cleaning crews serving Brooklyn offices, retail, and warehouses.",
    list: [
      "Local Brooklyn Crews",
      "Fully Insured & Bonded",
      "Custom Cleaning Schedules",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 7,
    pageName: "commercial-cleaning-queens",
    title: "Queens Commercial Cleaning",
    subtitle: "Commercial Cleaning Services in Queens, NY",
    desc: "Reliable commercial cleaning for Queens offices, warehouses, and retail spaces.",
    list: [
      "Local Queens Crews",
      "Fully Insured & Bonded",
      "Custom Cleaning Schedules",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 8,
    pageName: "commercial-cleaning-bronx",
    title: "Bronx Commercial Cleaning",
    subtitle: "Commercial Cleaning Services in the Bronx, NY",
    desc: "Trusted commercial cleaning crews for Bronx offices, facilities, and retail spaces.",
    list: [
      "Local Bronx Crews",
      "Fully Insured & Bonded",
      "Custom Cleaning Schedules",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 9,
    pageName: "commercial-cleaning-staten-island",
    title: "Staten Island Commercial Cleaning",
    subtitle: "Commercial Cleaning Services on Staten Island",
    desc: "Reliable commercial cleaning for Staten Island offices, retail, and facilities.",
    list: [
      "Local Staten Island Crews",
      "Fully Insured & Bonded",
      "Custom Cleaning Schedules",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  {
    id: 10,
    pageName: "commercial-cleaning-long-island",
    title: "Long Island Commercial Cleaning",
    subtitle: "Commercial Cleaning Services Across Long Island",
    desc: "Trusted commercial cleaning crews serving Long Island offices, retail, and facilities.",
    list: [
      "Local Long Island Crews",
      "Fully Insured & Bonded",
      "Custom Cleaning Schedules",
      "Dedicated Account Manager",
    ],
    steps: [
      {
        id: 1,
        score: 200,
        sign: "+",
        title: "PROJECTS COMPLETED",
      },
      {
        id: 2,
        score: 24,
        sign: "Hrs",
        title: "FAST QUOTING",
      },
      {
        id: 3,
        score: 100,
        sign: "%",
        title: "LICENSED & INSURED",
      },
      {
        id: 4,
        score: 98,
        sign: "%",
        title: "Happy\nCustomers",
      },
    ],
    services: [
      {
        id: 1,
        title: "Break Room Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 2,
        title: "Lobby Entrance Floor",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
      {
        id: 3,
        title: "Restroom Deep Clean",
        beforeImage: "/images/quotes/janitorial/janitorial-after01.jpeg",
        afterImage: "/images/quotes/janitorial/janitorial-before01.png",
      },
    ],
  },
  
];